# Generated by Django 3.2.11 on 2022-02-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_structure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description of position'),
        ),
    ]
