# Generated by Django 3.2.11 on 2022-02-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_structure', '0002_position_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description of department'),
        ),
    ]
