# Generated by Django 3.2.11 on 2022-02-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_structure', '0003_department_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='slug',
            field=models.SlugField(default='slug', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='position',
            name='slug',
            field=models.SlugField(default='slug_name', max_length=150),
        ),
    ]
