# Generated by Django 3.2.11 on 2022-02-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_structure', '0004_auto_20220202_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='slug',
            field=models.SlugField(max_length=150),
        ),
    ]
